language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  allow_failures:
    - rvm: 2.2
sudo: false
cache: bundler
branches:
  except:
    - 1-0-stable
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
